apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: wely-dev

# On peut ici ajouter des préfixes aux noms ou modifier des variables spécifiques au dev
namePrefix: dev-
images:
- name: ghcr.io/welylabs/wely-events
  newName: ghcr.io/welylabs/wely-events
  newTag: sha-db9d3c66d713309f6d0a01712a1bbdccd57ab755
- name: ghcr.io/welylabs/wely-gateway
  newName: ghcr.io/welylabs/wely-gateway
  newTag: sha-edd7b091611b2cec1f5ba1e1231f05ae45aed907
- name: ghcr.io/welylabs/wely-social
  newName: ghcr.io/welylabs/wely-social
  newTag: sha-856b83d775c7e627d6eb9befd8f7d0012e70b6e0
- name: ghcr.io/welylabs/wely-users
  newName: ghcr.io/welylabs/wely-users
  newTag: sha-726b0a9eff53ceda058d26508edf57b8d03bce7a
