apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- wely-secrets-local.yaml
- namespace.yaml
- wely-users-alias.yaml

namespace: wely-local

namePrefix: local-

configMapGenerator:
- name: keycloak-init-sql
  files:
  - keycloak-init.sql
- name: users-init-sql
  files:
  - users-init.sql

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: keycloak-init-volume
        configMap:
          name: keycloak-init-sql
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: keycloak-init-volume
        mountPath: /docker-entrypoint-initdb.d
  target:
    kind: StatefulSet
    name: wely-postgres-auth
- patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: users-init-volume
        configMap:
          name: users-init-sql
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: users-init-volume
        mountPath: /docker-entrypoint-initdb.d
  target:
    kind: StatefulSet
    name: wely-postgres-users
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "http://local-wely-gateway-service.wely-local.svc.cluster.local:8081"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: KEYCLOAK_URL
        value: "http://localhost:8080"
  target:
    kind: Deployment
    name: wely-web
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
  target:
    kind: Service
    name: wely-web-service
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
  target:
    kind: Service
    name: wely-gateway-service
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
  target:
    kind: Service
    name: wely-auth-service
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "http://localhost:8080/realms/calendar-app"
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "http://local-wely-users-service:8082"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "http://local-wely-social-service:8083"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "http://local-wely-chat-service:8084"
    - op: replace
      path: /spec/template/spec/containers/0/env/6/value
      value: "ws://local-wely-chat-service:8084"
    - op: replace
      path: /spec/template/spec/containers/0/env/7/value
      value: "http://local-wely-events-service:8086"
    - op: replace
      path: /spec/template/spec/containers/0/env/9/value
      value: "http://localhost,http://localhost:80,http://localhost:4200"
  target:
    kind: Deployment
    name: wely-gateway
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "r2dbc:postgresql://local-wely-postgres-users-service:5432/users"
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "http://localhost:8080/realms/calendar-app"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/token"
    - op: replace
      path: /spec/template/spec/containers/0/env/6/value
      value: "http://local-wely-auth-service:8080"
    - op: replace
      path: /spec/template/spec/containers/0/env/9/value
      value: "local-wely-kafka-service:9092"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
        value: "PLAINTEXT"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SECURITY_PROTOCOL
        value: "PLAINTEXT"
  target:
    kind: Deployment
    name: wely-users
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "neo4j://local-wely-neo4j-service:7687"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "local-wely-kafka-service:9092"
    - op: replace
      path: /spec/template/spec/containers/0/env/7/value
      value: "http://localhost:8080/realms/calendar-app"
    - op: replace
      path: /spec/template/spec/containers/0/env/8/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
        value: "PLAINTEXT"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SECURITY_PROTOCOL
        value: "PLAINTEXT"
  target:
    kind: Deployment
    name: wely-social
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@local-wely-mongodb-service:27017/chat_db?authSource=admin"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "http://localhost:8080/realms/calendar-app"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
  target:
    kind: Deployment
    name: wely-chat
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@local-wely-mongodb-service:27017/events_db?authSource=admin"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "http://localhost:8080/realms/calendar-app"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "http://local-wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
  target:
    kind: Deployment
    name: wely-events
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cloudflared-connector
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "localhost"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "false"
    - op: replace
      path: /spec/template/spec/containers/0/env/7/value
      value: "jdbc:postgresql://local-wely-postgres-auth-service:5432/keycloak"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: USERS_API_URL
        value: "http://local-wely-users-service:8082"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: USERS_SERVICE_URL
        value: "http://local-wely-users-service:8082"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENVIRONMENT
        value: "local"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PROFILE
        value: "local"
  target:
    kind: Deployment
    name: wely-auth
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "PLAINTEXT://local-wely-kafka-service:9092"
  target:
    kind: Deployment
    name: wely-kafka
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "local-wely-kafka-service:9092"
  target:
    kind: Deployment
    name: wely-kafka-ui
patchesJson6902:
- target:
    group: ""
    version: v1
    kind: Service
    name: local-wely-users-service-alias
  patch: |-
    - op: replace
      path: /metadata/name
      value: wely-users-service

images:
- name: ghcr.io/welylabs/wely-chat
  newName: ghcr.io/welylabs/wely-chat
  newTag: sha-fc2bdc5424ac9e4e5b4f668aa8cb578d805b73f4
- name: ghcr.io/welylabs/wely-events
  newName: ghcr.io/welylabs/wely-events
  newTag: sha-16bc7fea8a482a70a37d28f512423b49841cb996
- name: ghcr.io/welylabs/wely-gateway
  newName: ghcr.io/welylabs/wely-gateway
  newTag: sha-894eb6976a24bb09b56d0ff7a0200b16c3a9ae14
- name: ghcr.io/welylabs/wely-keycloak
  newName: ghcr.io/welylabs/wely-keycloak
  newTag: sha-ad7e3bdfe69016b4ad986cec8510adfb9fa74f0b
- name: ghcr.io/welylabs/wely-social
  newName: ghcr.io/welylabs/wely-social
  newTag: sha-d4741cd539fb8fbda90761b4b4d6e41dd617234f
- name: ghcr.io/welylabs/wely-users
  newName: ghcr.io/welylabs/wely-users
  newTag: sha-c1d55374e1d178fc55b6344c74ae72c74b8a4d9b
- name: ghcr.io/welylabs/wely-web
  newName: ghcr.io/welylabs/wely-web
  newTag: sha-8a5fb9a083142d5fd91d5a44cd9f6acc6f451182
