apiVersion: v1
kind: Secret
metadata:
  name: dev-wely-secrets-dev
type: Opaque
stringData:
  # Auth Database
  auth-db-username: keycloak
  auth-db-password: local-secret-kc
  
  # Keycloak Admin & Client
  kc-admin-username: admin
  kc-admin-password: admin
  kc-client-secret: ainh6bJBpFuazwikbnc9WiZsLq7hOI38
  
  # Users Database
  users-db-username: users
  users-db-password: local-secret-users
  
  # Neo4j Database
  neo4j-username: neo4j
  neo4j-password: local-secret-neo4j
  
  # MongoDB Database
  mongo-root-username: admin
  mongo-root-password: local-secret-mongo
  
  # Kafka
  kafka-key: 7T6TBECWYDRYRW34
  kafka-secret: cfltxmSPAr6Kr3oJdDxffNf+FQ7unenW3hoHahIh/oDRVd6aZpgvM03Qdjk2KSRw
  
  # Tailscale Operator (OAuth)
  tailscale-client-id: "placeholder-id"
  tailscale-client-secret: "placeholder-secret"
