apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wely-neo4j
  labels:
    app: wely
    component: neo4j
spec:
  serviceName: "wely-neo4j-service"
  replicas: 1
  selector:
    matchLabels:
      app: wely-neo4j
  template:
    metadata:
      labels:
        app: wely-neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5
        ports:
        - containerPort: 7687
        - containerPort: 7474
        env:
        - name: MY_NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-wely-secrets-dev
              key: neo4j-password
        - name: NEO4J_AUTH
          value: "neo4j/$(MY_NEO4J_PASSWORD)"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wely-neo4j-service
spec:
  selector:
    app: wely-neo4j
  ports:
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
