apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator
rules:
  - apiGroups: [""]
    resources: ["namespaces", "services", "services/status", "pods", "endpoints", "secrets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
  - apiGroups: ["tailscale.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator
subjects:
  - kind: ServiceAccount
    name: tailscale-operator
roleRef:
  kind: ClusterRole
  name: tailscale-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wely-tailscale-operator
  labels:
    app: wely
    component: tailscale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wely-tailscale-operator
  template:
    metadata:
      labels:
        app: wely-tailscale-operator
    spec:
      serviceAccountName: tailscale-operator
      containers:
      - name: tailscale-operator
        image: tailscale/k8s-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dev-wely-secrets-dev
              key: tailscale-client-id
              optional: true
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dev-wely-secrets-dev
              key: tailscale-client-secret
              optional: true
        - name: OPERATOR_HOSTNAME
          value: "wely-k8s-operator"
