apiVersion: apps/v1
kind: Deployment
metadata:
  name: wely-chat
  labels:
    app: wely
    component: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wely-chat
  template:
    metadata:
      labels:
        app: wely-chat
    spec:
      containers:
      - name: chat
        image: ghcr.io/welylabs/wely-chat:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: wely-secrets
              key: mongodb-uri-chat
        - name: KEYCLOAK_ISSUER_URI
          value: "https://auth.welylabs.app/realms/calendar-app"
        - name: KEYCLOAK_INTERNAL_JWK_SET_URI
          value: "http://wely-auth-service:8080/realms/calendar-app/protocol/openid-connect/certs"
---
apiVersion: v1
kind: Service
metadata:
  name: wely-chat-service
spec:
  selector:
    app: wely-chat
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort
